### ISSUE TITLE
Next release: fully automated option

### ISSUE THREAD

**Issue by nathanbirrell** [facebookarchive/huxley#45]
Would it be possible for Huxley to automatically run through each webpage, without any action from the user (including rerecord) when specified?

In the Huxleyfile, an option like `autorecord=true` could be added for each test, which would mean on pages where no GUI changes majorly, testing is much faster.

**Comment by chenglou** [comment]
How would that work though? As in, just let huxley take a screen shot by itself and move on?

**Comment by nathanbirrell** [comment]
Yes, without user input. Would that be possible?

**Comment by chenglou** [comment]
Of course, though I'm not not sure how useful it is since you can copy paste a record file over to achieve that

**Comment by nathanbirrell** [comment]
Sorry, I mean when recording, rather than opening the browser, having to hit enter and then enter again to rerecord, couldn't that be automated for pages which have no changing UI elements?

**Comment by chenglou** [comment]
Oh, sorry misunderstood. You can't take the screen shot without opening the browser, at least not with selenium (which powers Huxley) afaik? So you can only save two or three keystrokes.

(FYI: with the current implementation, the first batch of screen shot (during recording) is actually discarded because of input fields focus aura (the auto rerecording defocuses all)).

**Comment by nathanbirrell** [comment]
Ah, okay. Thanks @chenglou.
